// Generates config.js from environment variables.
// Priority: real env vars (Vercel) > client/.env file (local) > defaults.
const fs = require("fs");
const path = require("path");

function loadDotEnv() {
  const envPath = path.join(__dirname, ".env");
  if (!fs.existsSync(envPath)) return {};
  const out = {};
  for (const line of fs.readFileSync(envPath, "utf-8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

const dotenv = loadDotEnv();
const BACKEND_URL =
  process.env.BACKEND_URL || dotenv.BACKEND_URL || "https://toolkit-scout.onrender.com";
const LOCAL_BACKEND_URL =
  process.env.LOCAL_BACKEND_URL || dotenv.LOCAL_BACKEND_URL || "http://localhost:5001";

const config = `// GENERATED by make-config.js — do not edit by hand.
window.CONFIG = {
  BACKEND_URL: ${JSON.stringify(BACKEND_URL)},
  LOCAL_BACKEND_URL: ${JSON.stringify(LOCAL_BACKEND_URL)},
};
`;

fs.writeFileSync(path.join(__dirname, "config.js"), config);
console.log(`config.js written (BACKEND_URL=${BACKEND_URL})`);
